survival-shooter
├── src
│   ├── main.py
│   ├── game
│   │   ├── __init__.py
│   │   ├── player.py
│   │   ├── enemy.py
│   │   └── weapon.py
│   ├── assets
│   │   └── __init__.py
│   └── utils
│       ├── __init__.py
│       └── constants.py
|
├── pyproject.toml
└── README.md